### ISSUE TITLE
is it possible to have a crop which is not centered?

### ISSUE THREAD

**Issue by gb5256** [pavlinter/yii2-display-image2#1]
I do have lots of images and sometimes a centered crop is not the best option.
There seems to be an option in the IMAGE module to set where the crop is done.
Is there a way to achieve this with your extension?

Thanks!

**Comment by pavlinter** [comment]
You want create own resize option?
It is now possible to add own resize option. See [configuration](https://github.com/pavlinter/yii2-display-image2#configuration)

**Comment by gb5256** [comment]
Woooow, that is fast !!! but...
I have tried as you show in your example config without changing anything.
But I do not get it to work.
I have realized that all the @var need to be commented (please update the docs).
But it is still not working.
Can you confirm that it works as you show in the config example?

**Comment by pavlinter** [comment]
No time for documentation. This plugin is made for himself.
This plugin works more than 5 website.
Maybe he's right for you. Use static "pavlinter/yii2-display-image2": "0.0.4"
