### ISSUE TITLE
can i use this?

### ISSUE THREAD

**Issue by hooman-mirghasemi** [pavlinter/yii2-display-image2#2]
hi, you replay to me : Thanks. This plugin not supported. You can use https://github.com/pavlinter/yii2-display-image2

but as i seen this repo have not release and all of release are pre-release.
can i use this ext ? is this contain all https://github.com/pavlinter/yii2-display-image method and can i replace display-image1 with display-image2 or i should wait until a release tag ?

**Comment by pavlinter** [comment]
You can use fixed version (example: 0.3.1). I use  https://github.com/pavlinter/yii2-display-image2 already in more 10 sites and work fine.
https://github.com/pavlinter/yii2-display-image is incompatible with  https://github.com/pavlinter/yii2-display-image2. You need update your site!
