### ISSUE TITLE
appendTimestamp

### ISSUE THREAD

**Issue by hooman-mirghasemi** [pavlinter/yii2-display-image2#5]
Hello. If it is possible,add a variable to config that it is decided to execute the appendTimestamp function or not.
Because in some cases, like our project, it's not necessary to run this function at all, because all the photos are added "timestamp" to their name when uploaded. and ?v=353454364 make some problems in our android project.

**Comment by pavlinter** [comment]
* Added
```php
'modules' => [
  'display2'=> [
      'class'=>'pavlinter\display2\Module',
      'appendTimestamp' => false,
      ....
 ],
],
