### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by hooman-mirghasemi** [pavlinter/yii2-display-image2#6]
When I check my site that used this ext, in gtmetrix.com
gtmetrix Optimize images for all of images generated with this extention: 
Losslessly compressing https://cdn1.mysite.com/images/display-images2-cache/user-avatar/200x200_inset_000000_100/avatar-15118591535733.jpg could save 2.8KiB (9% reduction). See optimized version.

all of images 11% reduction to 5% reduction!
What's your comment about changing in codes to generate better image for site loading time?

**Comment by hooman-mirghasemi** [comment]
@pavlinter

**Comment by pavlinter** [comment]
I would not want to use other services. And there's no time to study GTmetrix. You can create your fork. Sorry
